apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: $VIRTUAL_IP
    k8sServicePort: 6443
    autoDirectNodeRoutes: true
    bandwidthManager:
      bbr: true
      enabled: true
    bpf:
      hostLegacyRouting: false
    devices:
    - $INTERFACE
    enableIPv4BIGTCP: true
    envoy:
      enabled: true
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
          - BPF
          - NET_ADMIN
          - NET_BIND_SERVICE
    gatewayAPI:
      enabled: true
      hostNetwork:
        enabled: true
    ipv4NativeRoutingCIDR: 10.42.0.0/15
    loadBalancer:
      algorithm: maglev
    routingMode: native
