node-name: $NODE_NAME
server: https://$API_IP:9345
token: $TOKEN
data-dir: $RKE_DATA_DIR
disable: ['rke2-canal', 'rke2-ingress-nginx']
disable-cloud-controller: true
disable-kube-proxy: true
cni: cilium
tls-san:
- cluster.local
- $API_IP
- $PUBLIC_IP
