name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build Go binary
        run: |
          go build -o k8s-agent main.go

      - name: Package manifests and binary
        run: |
          mkdir release
          cp k8s-agent k8s-agent.service release/
          cp -r manifests release/
          tar -czvf package.tgz -C release .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: package.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
