name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.23'

      - name: Build Go binary
        run: |
          go build -o k8s-agent cmd/agent/main.go

      - name: Package manifests and binary
        run: |
          mkdir release
          cp k8s-agent release/
          cp -r configs manifests scripts release/
          tar -czvf package.tgz -C release .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: |
            install.sh
            package.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
